Traceback (most recent call last):
  File "/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/simulation_runs/two_sample/contiVsDisc/contiVsDisc_9.py", line 63, in <module>
    d_trend.to_csv("/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/simulation_runs/two_sample/contiVsDisc/contiVsDisc.csv")
NameError: name 'd_trend' is not defined
