Traceback (most recent call last):
  File "/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/simulation_runs/two_sample/mean_departure_n_trend.py", line 39, in <module>
    n_trend.loc[i,"power"] = (1/500)*tester.estimate_power(
  File "/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/modules/tester_new.py", line 208, in estimate_power
    tst_data_y = data_generator.generate_y()
  File "/mnt/nas/users/mjm/GitHub/private_conti_test/Python_implm/modules/tester_new.py", line 330, in generate_y
    normalSample = self.generator_y.sample( (self.n1,) )
  File "/mnt/nas/users/mjm/.local/lib/python3.8/site-packages/torch/distributions/distribution.py", line 136, in sample
    return self.rsample(sample_shape)
  File "/mnt/nas/users/mjm/.local/lib/python3.8/site-packages/torch/distributions/multivariate_normal.py", line 202, in rsample
    shape = self._extended_shape(sample_shape)
  File "/mnt/nas/users/mjm/.local/lib/python3.8/site-packages/torch/distributions/distribution.py", line 237, in _extended_shape
    sample_shape = torch.Size(sample_shape)
TypeError: torch.Size() takes an iterable of 'int' (item 0 is 'numpy.float64')
